Repository swent-group4/sudden-bump, pull requests merged in 2024-12, with the labels that each got.

#266 255 automaticly delete expired meetings from pendingmeetings
  app/src/androidTest/java/com/swent/suddenbump/ui/calendar/CalendarMeetingsTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/calendar/PendingMeetingsTest.kt
  app/src/main/java/com/swent/suddenbump/model/meeting/MeetingViewModel.kt
  app/src/main/java/com/swent/suddenbump/ui/calendar/CalendarMeetings.kt
  app/src/main/java/com/swent/suddenbump/ui/calendar/PendingMeetings.kt
  app/src/main/java/com/swent/suddenbump/worker/LocationUpdateWorker.kt
  app/src/test/java/com/swent/suddenbump/model/meeting/MeetingViewModelTest.kt
Labels: enhancement

#256 Prevent the navigation to the current screen
  app/src/main/java/com/swent/suddenbump/ui/navigation/NavigationActions.kt
Labels: bug

#253 242 choose who to share location with
  app/.attach_pid13268
  app/src/main/java/com/swent/suddenbump/model/user/UserRepository.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserViewModel.kt
  app/src/test/java/com/swent/suddenbump/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/swent/suddenbump/model/user/UserViewModelTest.kt
Labels: enhancement

#276 270 add meetings settings
  .github/workflows/ci.yml
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/MeetingsSettingsTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/SettingsScreenTest.kt
  app/src/main/java/com/swent/suddenbump/MainActivity.kt
  app/src/main/java/com/swent/suddenbump/model/meeting/MeetingViewModel.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/Settings.kt
  app/src/test/java/com/swent/suddenbump/model/meeting/MeetingViewModelTest.kt
Labels: enhancement

#282 Use notifications to allow/refuse location
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swent/suddenbump/ActionReceiver.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepository.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/swent/suddenbump/ui/map/Map.kt
  app/src/main/java/com/swent/suddenbump/worker/LocationUpdateWorker.kt
  app/src/test/java/com/swent/suddenbump/ActionReceiverTest.kt
  app/src/test/java/com/swent/suddenbump/model/NotificationTest.kt
  app/src/test/java/com/swent/suddenbump/model/user/UserRepositoryFirestoreTest.kt
Labels: enhancement

#283 update ui of overview screen to include location sharing toggle
  app/.attach_pid6683
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/OverviewScreenTest.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserViewModel.kt
  app/src/main/java/com/swent/suddenbump/ui/map/Map.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/FriendsList.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/Overview.kt
  app/src/main/res/drawable/baseline_location_off_24.xml
  app/src/main/res/drawable/baseline_location_on_24.xml
Labels: enhancement

#292 Fix Intent Collision, Enhance Notifications Appearance, and Refactor Settings & Database Interactions
  app/.attach_pid6683
  app/src/androidTest/java/com/swent/suddenbump/ui/endToEndTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/ConfidentialityScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/SettingsScreenTest.kt
  app/src/main/java/com/swent/suddenbump/MainActivity.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepository.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserViewModel.kt
  app/src/main/java/com/swent/suddenbump/ui/map/Map.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/ConfidentialityScreen.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/Settings.kt
  app/src/main/java/com/swent/suddenbump/worker/LocationUpdateWorker.kt
  app/src/test/java/com/swent/suddenbump/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/swent/suddenbump/model/user/UserViewModelTest.kt
Labels: bug, enhancement

#293 281 change meeting location to real addresses
  .github/workflows/ci.yml
  app/src/androidTest/java/com/swent/suddenbump/ui/calendar/AddMeetingScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/calendar/CalendarMeetingsTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/calendar/EditMeetingScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/calendar/PendingMeetingsTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/destination/MapScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/destination/SimpleMapTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/endToEndTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/utils/UiUtilsTest.kt
  app/src/main/java/com/swent/suddenbump/MainActivity.kt
  app/src/main/java/com/swent/suddenbump/model/meeting/Meeting.kt
  app/src/main/java/com/swent/suddenbump/model/meeting/MeetingRepositoryFirestore.kt
  app/src/main/java/com/swent/suddenbump/model/meeting/MeetingViewModel.kt
  app/src/main/java/com/swent/suddenbump/model/meeting_location/Location.kt
  app/src/main/java/com/swent/suddenbump/model/meeting_location/LocationRepository.kt
  app/src/main/java/com/swent/suddenbump/model/meeting_location/LocationViewModel.kt
  app/src/main/java/com/swent/suddenbump/model/meeting_location/NominatimLocationRepository.kt
  app/src/main/java/com/swent/suddenbump/ui/calendar/AddMeeting.kt
  app/src/main/java/com/swent/suddenbump/ui/calendar/CalendarMeetings.kt
  app/src/main/java/com/swent/suddenbump/ui/calendar/EditMeeting.kt
  app/src/main/java/com/swent/suddenbump/ui/calendar/PendingMeetings.kt
  app/src/main/java/com/swent/suddenbump/ui/map/Map.kt
  app/src/main/java/com/swent/suddenbump/ui/utils/SharedComponents.kt
  app/src/test/java/com/swent/suddenbump/model/NotificationTest.kt
  app/src/test/java/com/swent/suddenbump/model/meeting/MeetingRepositoryFirestoreTest.kt
  app/src/test/java/com/swent/suddenbump/model/meeting/MeetingViewModelTest.kt
  app/src/test/java/com/swent/suddenbump/model/meeting_location/LocationViewModelTest.kt
  app/src/test/java/com/swent/suddenbump/model/meeting_location/NominatimLocationRepositoryTest.kt
Labels: enhancement

#299 Refactor UI duplicated code
  app/src/main/java/com/swent/suddenbump/ui/authentication/SignUp.kt
  app/src/main/java/com/swent/suddenbump/ui/calendar/AddMeeting.kt
  app/src/main/java/com/swent/suddenbump/ui/calendar/EditMeeting.kt
  app/src/main/java/com/swent/suddenbump/ui/calendar/MeetingHelper.kt
  app/src/main/java/com/swent/suddenbump/ui/contact/AddContact.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/AccountScreen.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/BlockedUsersScreen.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/DiscussionScreen.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/Settings.kt
  app/src/main/java/com/swent/suddenbump/ui/utils/SharedComponents.kt
Labels: enhancement

#290 feat(offline mode) : now retrieves from cache when offline
  app/src/androidTest/java/com/swent/suddenbump/ui/MainActivityTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/OverviewScreenTest.kt
  app/src/main/java/com/swent/suddenbump/MainActivity.kt
  app/src/main/java/com/swent/suddenbump/model/image/ImageRepositoryFirebaseStorage.kt
  app/src/main/java/com/swent/suddenbump/model/location/LocationGetter.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserViewModel.kt
  app/src/main/java/com/swent/suddenbump/ui/authentication/SignUp.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/Overview.kt
  app/src/main/java/com/swent/suddenbump/ui/utils/isRunningTest.kt
  app/src/test/java/com/swent/suddenbump/model/image/ImageRepositoryFirebaseStorageTest.kt
  app/src/test/java/com/swent/suddenbump/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/swent/suddenbump/model/user/UserViewModelTest.kt
Labels: enhancement

#289 add logout functionnality to logout button
  .github/workflows/ci.yml
  Clean
  app/src/androidTest/java/com/swent/suddenbump/ui/endToEndTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/AccountScreenTest.kt
  app/src/main/java/com/swent/suddenbump/ActionReceiver.kt
  app/src/main/java/com/swent/suddenbump/MainActivity.kt
  app/src/main/java/com/swent/suddenbump/model/user/SharedPreferencesManager.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepository.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserViewModel.kt
  app/src/main/java/com/swent/suddenbump/ui/authentication/SignUp.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/AccountScreen.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/Overview.kt
  app/src/main/java/com/swent/suddenbump/worker/LocationUpdateWorker.kt
  app/src/main/java/com/swent/suddenbump/worker/WorkerScheduler.kt
  app/src/test/java/com/swent/suddenbump/model/user/SharedPreferencesManagerTest.kt
  app/src/test/java/com/swent/suddenbump/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/swent/suddenbump/model/user/UserViewModelTest.kt
Labels: enhancement

#302 Crop and compress profile picture in Settings
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/SettingsScreenTest.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/Settings.kt
Labels: enhancement

#309 Fix the release builder
  .github/workflows/gradle-build.yml
Labels: bug

#307 Fix bugs linked with overview screen
  app/src/main/java/com/swent/suddenbump/model/image/ImageRepositoryFirebaseStorage.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepositoryFirestore.kt
  app/src/test/java/com/swent/suddenbump/model/user/UserRepositoryFirestoreTest.kt
Labels: bug

#320 Refactor UserRepositoryFirestore Tests
  app/src/test/java/com/swent/suddenbump/model/user/UserRepositoryFirestoreTest.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/BlockedUserTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/MiscellaneousTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/PhoneNumberTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/RadiusNotifsTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/RecommendedFriendsTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/ShareLocationTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/UserAccountTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/UserFriendsRequestsTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/UserFriendsTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/UserStatusTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/VerifyNoAccountExistsTests.kt
Labels: enhancement

#310 Unsend friend request
  app/src/androidTest/java/com/swent/suddenbump/ui/contacts/ContactTest.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserViewModel.kt
  app/src/main/java/com/swent/suddenbump/ui/contact/ContactPage.kt
  app/src/test/java/com/swent/suddenbump/model/user/UserViewModelTest.kt
Labels: enhancement

#326 271 Make rounded userspictures , improve UI of the app and meeting notifications
  .github/workflows/ci.yml
  app/src/androidTest/java/com/swent/suddenbump/ui/calendar/CalendarMeetingsTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/calendar/PendingMeetingsTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/chat/ChatScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/contacts/ContactTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/OverviewScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/utils/UiUtilsTest.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepository.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/swent/suddenbump/ui/calendar/CalendarMeetings.kt
  app/src/main/java/com/swent/suddenbump/ui/calendar/EditMeeting.kt
  app/src/main/java/com/swent/suddenbump/ui/calendar/MeetingHelper.kt
  app/src/main/java/com/swent/suddenbump/ui/calendar/PendingMeetings.kt
  app/src/main/java/com/swent/suddenbump/ui/chat/Chat.kt
  app/src/main/java/com/swent/suddenbump/ui/contact/AddContact.kt
  app/src/main/java/com/swent/suddenbump/ui/contact/ContactPage.kt
  app/src/main/java/com/swent/suddenbump/ui/messages/Messages.kt
  app/src/main/java/com/swent/suddenbump/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/Overview.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/Settings.kt
  app/src/main/java/com/swent/suddenbump/ui/theme/Color.kt
  app/src/main/java/com/swent/suddenbump/ui/utils/SharedComponents.kt
  app/src/main/java/com/swent/suddenbump/worker/LocationUpdateWorker.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/MiscellaneousTests.kt
Labels: enhancement

#323 222 fixing network and messages features
  app/src/androidTest/java/com/swent/suddenbump/ui/chat/ChatScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/messages/MessagesScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/model/image/ImageRepositoryFirebaseStorageTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/AccountScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/utils/IsInternetAvailableTest.kt
  app/src/main/java/com/swent/suddenbump/model/chat/ChatSummary.kt
  app/src/main/java/com/swent/suddenbump/model/image/ImageRepositoryFirebaseStorage.kt
  app/src/main/java/com/swent/suddenbump/model/user/SharedPreferencesManager.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/swent/suddenbump/ui/messages/Messages.kt
  app/src/main/java/com/swent/suddenbump/ui/utils/isInternetAvailable.kt
  app/src/main/java/com/swent/suddenbump/ui/utils/isRunningTest.kt
  app/src/test/java/com/swent/suddenbump/model/chat/ChatSummaryTest.kt
  app/src/test/java/com/swent/suddenbump/model/image/ImageRepositoryFirebaseStorageTest.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/BlockedUserTests.kt
Labels: bug, enhancement

#331 Add app description inside README
  README.md
Labels: documentation

#330 Fix (0,0) location
  app/src/androidTest/java/com/swent/suddenbump/ui/MainActivityTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/calendar/CalendarMeetingsTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/calendar/PendingMeetingsTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/chat/ChatScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/contacts/AddContactTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/contacts/ContactTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/destination/MapScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/destination/SimpleMapTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/endToEndTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/messages/MessagesScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/BlockedUsersScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/OverviewScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/SettingsScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/utils/UiUtilsTest.kt
  app/src/main/java/com/swent/suddenbump/model/user/User.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserViewModel.kt
  app/src/main/java/com/swent/suddenbump/ui/authentication/SignUp.kt
  app/src/main/java/com/swent/suddenbump/ui/map/Map.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/FriendsList.kt
  app/src/main/java/com/swent/suddenbump/worker/LocationUpdateWorker.kt
  app/src/test/java/com/swent/suddenbump/model/NotificationTest.kt
  app/src/test/java/com/swent/suddenbump/model/chat/ChatSummaryTest.kt
  app/src/test/java/com/swent/suddenbump/model/user/UserViewModelTest.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/BlockedUserTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/MiscellaneousTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/PhoneNumberTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/RadiusNotifsTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/RecommendedFriendsTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/ShareLocationTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/UserAccountTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/UserFriendsRequestsTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/UserFriendsTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/UserStatusTests.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/VerifyNoAccountExistsTests.kt
Labels: bug

#338 End-to-End test 3
  app/src/androidTest/java/com/swent/suddenbump/ui/endToEndTest.kt
  app/src/main/java/com/swent/suddenbump/ui/contact/ContactPage.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/Settings.kt
Labels: enhancement

#345 Add 4th end to end test
  app/src/androidTest/java/com/swent/suddenbump/ui/endToEndTest.kt
Labels: enhancement

#335 Put Architecture Diagram inside Readme
  README.md
Labels: documentation

#350 Add screenshot of the app to the readme
  README.md
Labels: enhancement

#356 fix flashing UI bugs in Overview.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/endToEndTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/AccountScreenTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/MeetingsSettingsTest.kt
  app/src/androidTest/java/com/swent/suddenbump/ui/overview/OverviewScreenTest.kt
  app/src/main/java/com/swent/suddenbump/MainActivity.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepository.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserRepositoryFirestore.kt
  app/src/main/java/com/swent/suddenbump/model/user/UserViewModel.kt
  app/src/main/java/com/swent/suddenbump/ui/map/Map.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/AccountScreen.kt
  app/src/main/java/com/swent/suddenbump/ui/overview/Overview.kt
  app/src/test/java/com/swent/suddenbump/model/user/UserViewModelTest.kt
  app/src/test/java/com/swent/suddenbump/model/user/userRepositoryFirestoreTests/MiscellaneousTests.kt
Labels: bug, enhancement
